### ISSUE TITLE
Utah services are down

### ISSUE THREAD

**Issue by rclark** [ngds/service-notifications#2]
@lmusil @ccaudill See http://web2.nbmg.unr.edu/arcgis/rest/services/UT_Data.

**Comment by ccaudill** [comment]
All NV-hosted services are down. Contacted Gary.

**Comment by ccaudill** [comment]
Gary's NV-hosted services are back up and running.

Sent from my iPhone

On Dec 12, 2013, at 10:47 AM, "Ryan Clark" <notifications@github.com<mailto:notifications@github.com>> wrote:

@lmusilhttps://github.com/lmusil @ccaudillhttps://github.com/ccaudill See http://web2.nbmg.unr.edu/arcgis/rest/services/UT_Data.

##
