### ISSUE TITLE
Illinois server is down.

### ISSUE THREAD

**Issue by krichards4** [ngds/service-notifications#7]
I keep getting an Invalid URL for all services I try viewing.

**Comment by ccaudill** [comment]
Check the services to make sure they're working. If not, contact Melony.

Sent from my iPhone

On Jan 1, 2014, at 9:52 AM, "Ken Richards" <notifications@github.com<mailto:notifications@github.com>> wrote:

I keep getting an Invalid URL for all services I try viewing.

##

**Comment by krichards4** [comment]
Server was restarted by Melony.
